"""Motion, graphics and sound design for the space channel.

Everything here is generated by code at render time, so it costs nothing and
nothing is licensed from anyone:

- data cards: an animated counter ("0 → 465 degrees"), a true-scale comparison
  (two discs, the small one shrinking to a dot) and a live countdown, drawn
  with PIL as a transparent PNG sequence and overlaid on the shot;
- point-of-view effects: blackout (vignette closing, picture dimming),
  shake with a red flash, pressure (hard push-in), chosen by the writer per
  shot and triggered exactly when the sentence is spoken;
- sound design: whooshes on cuts, a thump on danger beats, a heartbeat under
  countdowns, synthesised with numpy and mixed under the narration;
- video shots: real footage (NASA clips) cropped to 9:16 around the focus
  point with a slow push, looped when the clip is shorter than the beat.
"""

from __future__ import annotations

import math
import random
import subprocess
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

from .voice import RATE, write_wave

WIDTH, HEIGHT, FPS = 1080, 1920, 30
GRAPHIC_TYPES = {"counter", "scale", "countdown"}
EFFECT_TYPES = {"blackout", "shake", "pressure", "flash"}


def _font(size):
    for path in ("/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf",
                 "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"):
        if Path(path).is_file():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def _ease(x):
    return 1 - (1 - x) ** 3


def _text(draw, xy, text, size, fill, anchor="mm", stroke=0):
    draw.text(xy, text, font=_font(size), fill=fill, anchor=anchor,
              stroke_width=stroke, stroke_fill=(0, 0, 0, 255))


# ------------------------------------------------------------------ graphics
def validate_graphic(value):
    """Writer-supplied graphic spec → clean dict or None."""
    if not isinstance(value, dict):
        return None
    kind = str(value.get("type", "")).casefold()
    if kind not in GRAPHIC_TYPES:
        return None
    try:
        if kind == "counter":
            number = float(value.get("value"))
            if not math.isfinite(number) or abs(number) > 1e15:
                return None
            return {"type": "counter", "value": number, "unit": str(value.get("unit", ""))[:24],
                    "label": str(value.get("label", ""))[:40]}
        if kind == "scale":
            ratio = float(value.get("ratio"))
            if not 1.5 <= ratio <= 1e9:
                return None
            return {"type": "scale", "big": str(value.get("big", ""))[:24], "small": str(value.get("small", ""))[:24],
                    "ratio": ratio, "label": str(value.get("label", ""))[:40]}
        seconds = int(float(value.get("seconds")))
        if not 1 <= seconds <= 999:
            return None
        return {"type": "countdown", "seconds": seconds, "label": str(value.get("label", ""))[:40]}
    except (TypeError, ValueError):
        return None


def _fmt(number):
    if abs(number) >= 1000:
        return f"{number:,.0f}"
    if number == int(number):
        return str(int(number))
    return f"{number:.2f}".rstrip("0").rstrip(".")


def _card_background(draw, box, alpha=150):
    draw.rounded_rectangle(box, radius=38, fill=(0, 0, 0, alpha), outline=(255, 214, 10, 200), width=4)


def graphic_frames(graphic, frames, out_dir):
    """Transparent PNG sequence for one shot's graphic overlay."""
    out_dir.mkdir(parents=True, exist_ok=True)
    kind = graphic["type"]
    rise = max(8, min(frames - 4, round(frames * 0.55)))
    for n in range(frames):
        layer = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
        draw = ImageDraw.Draw(layer)
        appear = min(1.0, n / 6)  # quick fade/scale in
        if kind == "counter":
            p = _ease(min(1.0, n / rise))
            value = graphic["value"] * p
            if graphic["value"] == int(graphic["value"]):
                value = round(value)
            box = (90, 1180, WIDTH - 90, 1470)
            _card_background(draw, box, int(150 * appear))
            _text(draw, (WIDTH // 2, 1285), _fmt(value) + (" " + graphic["unit"] if graphic["unit"] else ""), 118,
                  (255, 214, 10, int(255 * appear)), stroke=5)
            if graphic["label"]:
                _text(draw, (WIDTH // 2, 1405), graphic["label"].upper(), 44, (255, 255, 255, int(230 * appear)), stroke=3)
        elif kind == "scale":
            p = _ease(min(1.0, n / rise))
            big_r = 150
            ratio = graphic["ratio"]
            small_r = max(5.0, big_r / (1 + (ratio - 1) * p))
            box = (90, 1120, WIDTH - 90, 1500)
            _card_background(draw, box, int(150 * appear))
            cx_big, cx_small, cy = 330, 760, 1300
            draw.ellipse((cx_big - big_r, cy - big_r, cx_big + big_r, cy + big_r), fill=(255, 170, 30, int(255 * appear)))
            draw.ellipse((cx_small - small_r, cy - small_r, cx_small + small_r, cy + small_r), fill=(80, 170, 255, int(255 * appear)))
            if small_r <= 12:
                ring = 26
                draw.ellipse((cx_small - ring, cy - ring, cx_small + ring, cy + ring), outline=(255, 255, 255, int(200 * appear)), width=2)
            _text(draw, (cx_big, cy + big_r + 36), graphic["big"].upper(), 40, (255, 255, 255, int(230 * appear)), stroke=3)
            _text(draw, (cx_small, cy + big_r + 36), graphic["small"].upper(), 40, (255, 255, 255, int(230 * appear)), stroke=3)
            _text(draw, (WIDTH // 2, 1160), f"{_fmt(ratio)}x", 60, (255, 214, 10, int(255 * appear)), stroke=4)
        else:  # countdown
            total = graphic["seconds"]
            seconds_per_frame = total / max(1, frames)
            remaining = max(0.0, total - n * seconds_per_frame)
            size = 150
            cx, cy, r = WIDTH - 200, 330, 125
            draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=(0, 0, 0, int(160 * appear)), outline=(255, 60, 60, int(230 * appear)), width=8)
            sweep = 360 * (remaining / total)
            draw.arc((cx - r + 4, cy - r + 4, cx + r - 4, cy + r - 4), start=-90, end=-90 + sweep, fill=(255, 214, 10, int(255 * appear)), width=10)
            _text(draw, (cx, cy - 6), str(int(math.ceil(remaining))), size if remaining >= 10 else size + 20,
                  (255, 255, 255, int(255 * appear)), stroke=5)
            if graphic["label"]:
                _text(draw, (cx, cy + r + 40), graphic["label"].upper(), 34, (255, 255, 255, int(230 * appear)), stroke=3)
        layer.save(out_dir / f"card_{n:04d}.png", "PNG", compress_level=1)
    return out_dir


# ------------------------------------------------------------------- effects
def effect_filters(effect, frames):
    """ffmpeg filters appended after the motion filter for one shot."""
    if effect not in EFFECT_TYPES:
        return []
    duration = max(0.1, frames / FPS)
    if effect == "blackout":
        return [f"eq=brightness='-0.9*min(1,t/{duration:.3f})':saturation='1-0.8*min(1,t/{duration:.3f})'",
                f"vignette=angle='PI/5+PI/3.2*min(1,t/{duration:.3f})'"]
    if effect == "shake":
        shake = 10
        return [f"scale={WIDTH + 2 * shake}:{HEIGHT + 2 * shake}",
                f"crop={WIDTH}:{HEIGHT}:x='{shake}+{shake}*sin(n*5.3)*exp(-n/14)':y='{shake}+{shake}*cos(n*7.1)*exp(-n/14)'",
                f"drawbox=c=red@0.45:t=fill:enable='lt(n,5)'"]
    if effect == "flash":
        return [f"drawbox=c=white@0.85:t=fill:enable='lt(n,3)'", f"drawbox=c=white@0.4:t=fill:enable='between(n,3,5)'"]
    # pressure: hard push-in over the shot
    return [f"scale='iw*(1+0.35*min(1,t/{duration:.3f}))':'ih*(1+0.35*min(1,t/{duration:.3f}))':eval=frame",
            f"crop={WIDTH}:{HEIGHT}", f"vignette=angle='PI/4.5+PI/5*min(1,t/{duration:.3f})'"]


# --------------------------------------------------------------- video shots
def video_filter(frames, focus, zoom_amount=0.08):
    """Real footage → 9:16 around the focus point with a slow push."""
    fx = min(1.0, max(0.0, float(focus[0]))) if focus else 0.5
    fy = min(1.0, max(0.0, float(focus[1]))) if focus else 0.5
    duration = max(0.1, frames / FPS)
    # Fit the short side, then crop; the crop window drifts with a slow zoom.
    return (
        f"scale='if(gt(a,{WIDTH}/{HEIGHT}),-2,{WIDTH}*(1+{zoom_amount}))':'if(gt(a,{WIDTH}/{HEIGHT}),{HEIGHT}*(1+{zoom_amount}),-2)':eval=init,"
        f"crop={WIDTH}:{HEIGHT}:x='(iw-{WIDTH})*{fx:.3f}':y='(ih-{HEIGHT})*{fy:.3f}',"
        f"zoompan=z='1+{zoom_amount}*min(1,on/{frames})':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s={WIDTH}x{HEIGHT}:fps={FPS},"
        f"eq=contrast=1.08:saturation=1.12,setsar=1,format=yuv420p"
    )


# ---------------------------------------------------------------------- sfx
def _noise(n, rng):
    return rng.standard_normal(n)


def whoosh(duration=0.42, rng=None):
    rng = rng or np.random.default_rng(3)
    n = round(duration * RATE)
    t = np.arange(n) / RATE
    noise = _noise(n, rng)
    # band-passed noise with a rising then falling envelope and a pitch sweep feel
    out = np.zeros(n)
    alpha_lo, alpha_hi = 0.02, 0.35
    lo = 0.0
    for i in range(n):
        a = alpha_lo + (alpha_hi - alpha_lo) * (t[i] / duration)
        lo += a * (noise[i] - lo)
        out[i] = lo
    env = np.sin(np.pi * t / duration) ** 1.5
    out = out * env
    return out / (np.max(np.abs(out)) or 1)


def thump(duration=0.5):
    n = round(duration * RATE)
    t = np.arange(n) / RATE
    freq = 70 * np.exp(-t * 6) + 38
    out = np.sin(2 * np.pi * np.cumsum(freq) / RATE) * np.exp(-t * 7)
    click = np.exp(-t * 400) * 0.6
    out = out + click
    return out / (np.max(np.abs(out)) or 1)


def heartbeat(duration):
    n = round(duration * RATE)
    out = np.zeros(n)
    beat = thump(0.35) * 0.9
    period = 0.85
    position = 0.0
    while position + 0.6 < duration:
        for offset in (0.0, 0.2):
            start = round((position + offset) * RATE)
            end = min(n, start + len(beat))
            out[start:end] += beat[: end - start] * (1.0 if offset == 0 else 0.6)
        position += period
    return out


def sfx_track(path, shots, timeline, duration, graphics):
    """Whoosh on every cut, a thump at danger beats, heartbeat under countdowns."""
    n = round(duration * RATE)
    out = np.zeros(n)
    rng = np.random.default_rng(11)

    def place(sample, at, gain):
        start = round(at * RATE)
        if start >= n or start < 0:
            return
        end = min(n, start + len(sample))
        out[start:end] += sample[: end - start] * gain

    for index, (shot, (start, end)) in enumerate(zip(shots, timeline)):
        if index:
            place(whoosh(0.38 + rng.uniform(0, 0.12), rng), start - 0.12, 0.55)
        if shot.get("emphasis") == "danger" or shot.get("effect") in {"shake", "flash"}:
            place(thump(), start, 0.9)
        graphic = graphics.get(index)
        if graphic and graphic["type"] == "countdown":
            place(heartbeat(end - start), start, 0.5)
    peak = np.max(np.abs(out)) or 1
    out = out / peak * 0.8
    write_wave(path, np.clip(out * 32767, -32768, 32767).astype("<i2"))
    return path


# --------------------------------------------------------------- video probe
def probe_duration(path):
    try:
        result = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of",
                                 "default=nw=1:nk=1", str(path)], capture_output=True, text=True, timeout=60)
        return float(result.stdout.strip())
    except (ValueError, subprocess.SubprocessError, OSError):
        return 0.0
